### ISSUE TITLE
How to have wordpress in a non-english language?

### ISSUE THREAD

**Issue by josal** [mchung/wordpress-on-heroku#11]
Hi,

thanks for this repo and your work.

I just need to know how to modify it in order to have the wordpress installation in spanish instead of english.

Thank you for your tips.

Kind regards,
Jose

**Comment by okko** [comment]
This feature is coming to the buildpack.

You might want to watch changes of https://github.com/mchung/heroku-buildpack-wordpress to see when it's available there.

You can test the Spanish WordPress now by using the frc copy of the buildpack and setting the language:

```
heroku labs:enable user-env-compile
heroku config:add BUILDPACK_URL=https://github.com/frc/heroku-buildpack-wordpress.git
heroku config:add WORDPRESS_LANGUAGE=es_ES
```

**Comment by okko** [comment]
You can use the buildpack to install the WordPress core files. It will always use the English for these, but it is okay as the language versions do not affect the core. So no changes to the buildpack are needed. You can then proceed to install the wanted language pack below your wp-content, and the combination will work.
