### ISSUE TITLE
no Cedar-supported app detected

### ISSUE THREAD

**Issue by Soundsauca** [mchung/wordpress-on-heroku#3]
Hi, thank you very much for your work on this, unfortunately I'm getting the following error. Are you able to help?

-----> Fetching custom git buildpack... done
 !     Heroku push rejected, no Cedar-supported app detected

To git@heroku.com:frozen-hollows-4097.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:frozen-hollows-4097.git'

**Comment by mchung** [comment]
Are you using this Wordpress template:

mchung/wordpress-on-heroku

On Saturday, April 6, 2013, ottobyte wrote:

> Hi, thank you very much for your work on this, unfortunately I'm getting
> the following error. Are you able to help?
> 
> -----> Fetching custom git buildpack... done
> ! Heroku push rejected, no Cedar-supported app detected
> 
> To git@heroku.com <javascript:_e({}, 'cvml', 'git@heroku.com');>
> :frozen-hollows-4097.git
> ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@heroku.com <javascript:_e({},
> 'cvml', 'git@heroku.com');>:frozen-hollows-4097.git'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mchung/wordpress-on-heroku/issues/3
> .

## 

Sent from Gmail Mobile

**Comment by Soundsauca** [comment]
My apologies, I had to verify billing info, now it works fine - Thanks very much!
