### ISSUE TITLE
blank page on facebook tab with wordpress/heroku

### ISSUE THREAD

**Issue by BenoitGirard** [mchung/wordpress-on-heroku#4]
I'm having issue trying to embed wordpress into facebook tab.
While the wordpress work very well outside of facebook, it does not render any HTML into facebook tab.
If I change the facebook tab URL of the APP with your exemple, it works!
(http://wordpress-on-heroku.herokuapp.com/)

I folllow your procedure step by step, is there any setting I'm missing?

**Comment by mchung** [comment]
What's the link you're using on FB? Did you try adding a custom domain to your heroku instance?

**Comment by BenoitGirard** [comment]
http://michelin-tab.herokuapp.com/

**Comment by BenoitGirard** [comment]
I removed the line add_header      X-Frame-Options SAMEORIGIN;  from wordpress.conf.erb
And it work! many thanks

**Comment by mchung** [comment]
Awesome. Can you either file me a ticket with a request to update the README, or update the README and send me a PR with something along those lines? It would help future users with this problem. Thanks.
