### ISSUE TITLE
Update to New Wordpress version (3.6)

### ISSUE THREAD

**Issue by kunjee17** [mchung/wordpress-on-heroku#6]
Hey, wordpress is updated to version 3.6. It is easy to update it form the application though but still it will be better if you push new source here only. Just to provide latest and greatest to user. Same is true for plugins. 

PS: I love the way you created build pack and this repo. Make it damn easy to use wordpress. Thanks

**Comment by mchung** [comment]
I updated the @mchung/heroku-buildpack-wordpress/ itself to 3.6.1

Thanks.
